### PR TITLE
feat: new Teams adaptive cards

### PR DESCRIPTION
**Pull request by Netail**
## Summary

New Teams adaptive cards to support Power Automate workflows

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by chrisjohnson00** [comment]
Yes, please!

**Comment by Netail** [comment]
> Yes, please!

Thanks for your support @chrisjohnson00 , I've been holding this back for a bit as the adaptive cards do not support colors (yet) But there might be work arounds.

You need adaptive cards for Microsoft power automate workflows? Regular webhook connectors still support the old format

**Comment by chrisjohnson00** [comment]
Why not just bake the color into the template as an image for now?

I'm not sure what we will end up using. I put this down, at work, as switching from a simple webhook to orchestrating a whole flow in power automate was far more work than expected. I need this all to work from a non human account, for security purposes, and doing that with power automate is decent effort and coordination for us.

Wishing they didn't kill the original hooks!

**Comment by Netail** [comment]
> Why not just bake the color into the template as an image for now?

I guess so, I've seen that a few times before. I'll try it out, will come back on that

> Wishing they didn't kill the original hooks! 

They actually brought it back to live (connectors), everyone had to update their webhook URL to a new one tho, which probably enters a different flow than it used to be. This URL supports both the new adaptive cards as the old ones, however power automate only supports the new adaptive cards

**Comment by Netail** [comment]
image

Looking good to me :)

vs the old

image

**Pull request merged**
